name: gitleaks and trufflehog
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *" # run once on day 1 of the month at 4 AM
jobs:
  scan:
    name: gitleaks-th3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
